id: P436F734E
initial_creation_type: input
source_metadata:
  Title: Hastabalapranavrtti
  Editor: Jain, Bhagchandra
  Publisher: Aloka Prakashan
  Place of Publication: Nagpur
  Year: '1971'
  Hastavālaprakaraṇa:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:37:53.641608'
last_modified_at: '2022-03-08T16:37:53.641616'
